-- Sample downstream Flyway DDL for conversation memories.
-- Upstream runtime initialization is handled by the Oracle writer's init_schema path.
-- UPDATED_AT only gets an INSERT default here and downstream update paths should
-- set it explicitly (or add a trigger) when status/content fields change.

CREATE TABLE CONVERSATION_MEMORIES (
    MEMORY_ID             VARCHAR2(255)            NOT NULL,
    CONVERSATION_ID       VARCHAR2(255)            NOT NULL,
    CONVERSATION_VERSION  NUMBER,
    RESPONSE_ID           VARCHAR2(255),
    MEMORY_TYPE           VARCHAR2(32)             NOT NULL,
    STATUS                VARCHAR2(32)             NOT NULL,
    ATTEMPT               NUMBER DEFAULT 0         NOT NULL,
    OWNER_ID              VARCHAR2(255),
    NEXT_RUN_AT           TIMESTAMP WITH TIME ZONE NOT NULL,
    LEASE_UNTIL           TIMESTAMP WITH TIME ZONE,
    CONTENT               CLOB,
    MEMORY_CONFIG         CLOB,
    SCOPE_ID              VARCHAR2(255),
    ERROR_MSG             CLOB,
    CREATED_AT            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_CONVERSATION_MEMORIES PRIMARY KEY (MEMORY_ID),
    CONSTRAINT CONV_MEM_STATUS_CK CHECK (STATUS IN ('READY', 'RUNNING', 'SUCCESS', 'FAILED')),
    CONSTRAINT CONV_MEM_TYPE_CK CHECK (MEMORY_TYPE IN ('ONDEMAND', 'LTM', 'STMO'))
);

CREATE INDEX IDX_CONV_MEMORIES_CONV_ID ON CONVERSATION_MEMORIES (CONVERSATION_ID);
CREATE INDEX IDX_CONV_MEMORIES_NEXT_RUN_AT ON CONVERSATION_MEMORIES (NEXT_RUN_AT);
CREATE INDEX IDX_CONV_MEMORIES_STATUS ON CONVERSATION_MEMORIES (STATUS);
CREATE INDEX IDX_CONV_MEMORIES_RESPONSE_ID ON CONVERSATION_MEMORIES (RESPONSE_ID);
