// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: vllm_engine.proto

package vllm_engine

import (
	common "github.com/lightseekorg/smg/crates/grpc_client/golang/smg_grpc_proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sampling parameters for text generation
type SamplingParams struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Temperature                *float32               `protobuf:"fixed32,1,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	TopP                       float32                `protobuf:"fixed32,2,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	TopK                       uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MinP                       float32                `protobuf:"fixed32,4,opt,name=min_p,json=minP,proto3" json:"min_p,omitempty"`
	FrequencyPenalty           float32                `protobuf:"fixed32,5,opt,name=frequency_penalty,json=frequencyPenalty,proto3" json:"frequency_penalty,omitempty"`
	PresencePenalty            float32                `protobuf:"fixed32,6,opt,name=presence_penalty,json=presencePenalty,proto3" json:"presence_penalty,omitempty"`
	RepetitionPenalty          float32                `protobuf:"fixed32,7,opt,name=repetition_penalty,json=repetitionPenalty,proto3" json:"repetition_penalty,omitempty"`
	MaxTokens                  *uint32                `protobuf:"varint,8,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	MinTokens                  uint32                 `protobuf:"varint,9,opt,name=min_tokens,json=minTokens,proto3" json:"min_tokens,omitempty"`
	Stop                       []string               `protobuf:"bytes,10,rep,name=stop,proto3" json:"stop,omitempty"`
	StopTokenIds               []uint32               `protobuf:"varint,11,rep,packed,name=stop_token_ids,json=stopTokenIds,proto3" json:"stop_token_ids,omitempty"`
	SkipSpecialTokens          bool                   `protobuf:"varint,12,opt,name=skip_special_tokens,json=skipSpecialTokens,proto3" json:"skip_special_tokens,omitempty"`
	SpacesBetweenSpecialTokens bool                   `protobuf:"varint,13,opt,name=spaces_between_special_tokens,json=spacesBetweenSpecialTokens,proto3" json:"spaces_between_special_tokens,omitempty"`
	IgnoreEos                  bool                   `protobuf:"varint,14,opt,name=ignore_eos,json=ignoreEos,proto3" json:"ignore_eos,omitempty"`
	N                          uint32                 `protobuf:"varint,15,opt,name=n,proto3" json:"n,omitempty"` // Number of parallel samples
	// Logprobs configuration
	Logprobs       *int32 `protobuf:"varint,22,opt,name=logprobs,proto3,oneof" json:"logprobs,omitempty"`                                   // Number of log probabilities per output token (-1 for all)
	PromptLogprobs *int32 `protobuf:"varint,23,opt,name=prompt_logprobs,json=promptLogprobs,proto3,oneof" json:"prompt_logprobs,omitempty"` // Number of log probabilities per prompt token (-1 for all)
	// Additional vLLM fields
	Seed                   *int32            `protobuf:"varint,24,opt,name=seed,proto3,oneof" json:"seed,omitempty"`                                                                                                  // Random seed for reproducibility
	IncludeStopStrInOutput bool              `protobuf:"varint,25,opt,name=include_stop_str_in_output,json=includeStopStrInOutput,proto3" json:"include_stop_str_in_output,omitempty"`                                // Whether to include stop strings in output
	LogitBias              map[int32]float32 `protobuf:"bytes,26,rep,name=logit_bias,json=logitBias,proto3" json:"logit_bias,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // Token ID to bias mapping (-100 to 100)
	TruncatePromptTokens   *int32            `protobuf:"varint,27,opt,name=truncate_prompt_tokens,json=truncatePromptTokens,proto3,oneof" json:"truncate_prompt_tokens,omitempty"`                                    // Prompt truncation (-1 for model max)
	// Structured outputs (one of) - matches vLLM's StructuredOutputsParams
	//
	// Types that are valid to be assigned to Constraint:
	//
	//	*SamplingParams_JsonSchema
	//	*SamplingParams_Regex
	//	*SamplingParams_Grammar
	//	*SamplingParams_StructuralTag
	//	*SamplingParams_JsonObject
	//	*SamplingParams_Choice
	Constraint    isSamplingParams_Constraint `protobuf_oneof:"constraint"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplingParams) Reset() {
	*x = SamplingParams{}
	mi := &file_vllm_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingParams) ProtoMessage() {}

func (x *SamplingParams) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplingParams.ProtoReflect.Descriptor instead.
func (*SamplingParams) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{0}
}

func (x *SamplingParams) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *SamplingParams) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *SamplingParams) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SamplingParams) GetMinP() float32 {
	if x != nil {
		return x.MinP
	}
	return 0
}

func (x *SamplingParams) GetFrequencyPenalty() float32 {
	if x != nil {
		return x.FrequencyPenalty
	}
	return 0
}

func (x *SamplingParams) GetPresencePenalty() float32 {
	if x != nil {
		return x.PresencePenalty
	}
	return 0
}

func (x *SamplingParams) GetRepetitionPenalty() float32 {
	if x != nil {
		return x.RepetitionPenalty
	}
	return 0
}

func (x *SamplingParams) GetMaxTokens() uint32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *SamplingParams) GetMinTokens() uint32 {
	if x != nil {
		return x.MinTokens
	}
	return 0
}

func (x *SamplingParams) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *SamplingParams) GetStopTokenIds() []uint32 {
	if x != nil {
		return x.StopTokenIds
	}
	return nil
}

func (x *SamplingParams) GetSkipSpecialTokens() bool {
	if x != nil {
		return x.SkipSpecialTokens
	}
	return false
}

func (x *SamplingParams) GetSpacesBetweenSpecialTokens() bool {
	if x != nil {
		return x.SpacesBetweenSpecialTokens
	}
	return false
}

func (x *SamplingParams) GetIgnoreEos() bool {
	if x != nil {
		return x.IgnoreEos
	}
	return false
}

func (x *SamplingParams) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *SamplingParams) GetLogprobs() int32 {
	if x != nil && x.Logprobs != nil {
		return *x.Logprobs
	}
	return 0
}

func (x *SamplingParams) GetPromptLogprobs() int32 {
	if x != nil && x.PromptLogprobs != nil {
		return *x.PromptLogprobs
	}
	return 0
}

func (x *SamplingParams) GetSeed() int32 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

func (x *SamplingParams) GetIncludeStopStrInOutput() bool {
	if x != nil {
		return x.IncludeStopStrInOutput
	}
	return false
}

func (x *SamplingParams) GetLogitBias() map[int32]float32 {
	if x != nil {
		return x.LogitBias
	}
	return nil
}

func (x *SamplingParams) GetTruncatePromptTokens() int32 {
	if x != nil && x.TruncatePromptTokens != nil {
		return *x.TruncatePromptTokens
	}
	return 0
}

func (x *SamplingParams) GetConstraint() isSamplingParams_Constraint {
	if x != nil {
		return x.Constraint
	}
	return nil
}

func (x *SamplingParams) GetJsonSchema() string {
	if x != nil {
		if x, ok := x.Constraint.(*SamplingParams_JsonSchema); ok {
			return x.JsonSchema
		}
	}
	return ""
}

func (x *SamplingParams) GetRegex() string {
	if x != nil {
		if x, ok := x.Constraint.(*SamplingParams_Regex); ok {
			return x.Regex
		}
	}
	return ""
}

func (x *SamplingParams) GetGrammar() string {
	if x != nil {
		if x, ok := x.Constraint.(*SamplingParams_Grammar); ok {
			return x.Grammar
		}
	}
	return ""
}

func (x *SamplingParams) GetStructuralTag() string {
	if x != nil {
		if x, ok := x.Constraint.(*SamplingParams_StructuralTag); ok {
			return x.StructuralTag
		}
	}
	return ""
}

func (x *SamplingParams) GetJsonObject() bool {
	if x != nil {
		if x, ok := x.Constraint.(*SamplingParams_JsonObject); ok {
			return x.JsonObject
		}
	}
	return false
}

func (x *SamplingParams) GetChoice() *ChoiceConstraint {
	if x != nil {
		if x, ok := x.Constraint.(*SamplingParams_Choice); ok {
			return x.Choice
		}
	}
	return nil
}

type isSamplingParams_Constraint interface {
	isSamplingParams_Constraint()
}

type SamplingParams_JsonSchema struct {
	JsonSchema string `protobuf:"bytes,16,opt,name=json_schema,json=jsonSchema,proto3,oneof"` // JSON schema for structured output
}

type SamplingParams_Regex struct {
	Regex string `protobuf:"bytes,17,opt,name=regex,proto3,oneof"` // Regex pattern
}

type SamplingParams_Grammar struct {
	Grammar string `protobuf:"bytes,18,opt,name=grammar,proto3,oneof"` // Grammar/EBNF for structured output
}

type SamplingParams_StructuralTag struct {
	StructuralTag string `protobuf:"bytes,19,opt,name=structural_tag,json=structuralTag,proto3,oneof"` // Structural tag (e.g., Harmony models)
}

type SamplingParams_JsonObject struct {
	JsonObject bool `protobuf:"varint,20,opt,name=json_object,json=jsonObject,proto3,oneof"` // Force JSON object output
}

type SamplingParams_Choice struct {
	Choice *ChoiceConstraint `protobuf:"bytes,21,opt,name=choice,proto3,oneof"` // List of allowed choices
}

func (*SamplingParams_JsonSchema) isSamplingParams_Constraint() {}

func (*SamplingParams_Regex) isSamplingParams_Constraint() {}

func (*SamplingParams_Grammar) isSamplingParams_Constraint() {}

func (*SamplingParams_StructuralTag) isSamplingParams_Constraint() {}

func (*SamplingParams_JsonObject) isSamplingParams_Constraint() {}

func (*SamplingParams_Choice) isSamplingParams_Constraint() {}

// Choice constraint for structured outputs
type ChoiceConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Choices       []string               `protobuf:"bytes,1,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChoiceConstraint) Reset() {
	*x = ChoiceConstraint{}
	mi := &file_vllm_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChoiceConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceConstraint) ProtoMessage() {}

func (x *ChoiceConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceConstraint.ProtoReflect.Descriptor instead.
func (*ChoiceConstraint) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{1}
}

func (x *ChoiceConstraint) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

// Pre-tokenized input from Rust router
type TokenizedInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalText  string                 `protobuf:"bytes,1,opt,name=original_text,json=originalText,proto3" json:"original_text,omitempty"` // For reference/debugging
	InputIds      []uint32               `protobuf:"varint,2,rep,packed,name=input_ids,json=inputIds,proto3" json:"input_ids,omitempty"`     // Actual token IDs to process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenizedInput) Reset() {
	*x = TokenizedInput{}
	mi := &file_vllm_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenizedInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenizedInput) ProtoMessage() {}

func (x *TokenizedInput) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenizedInput.ProtoReflect.Descriptor instead.
func (*TokenizedInput) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{2}
}

func (x *TokenizedInput) GetOriginalText() string {
	if x != nil {
		return x.OriginalText
	}
	return ""
}

func (x *TokenizedInput) GetInputIds() []uint32 {
	if x != nil {
		return x.InputIds
	}
	return nil
}

// A typed tensor: raw little-endian bytes + shape + dtype.
type TensorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`           // Raw little-endian bytes (f32/i64/u32)
	Shape         []uint32               `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"` // Dimension sizes
	Dtype         string                 `protobuf:"bytes,3,opt,name=dtype,proto3" json:"dtype,omitempty"`         // "float32", "int64", "uint32"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorData) Reset() {
	*x = TensorData{}
	mi := &file_vllm_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorData) ProtoMessage() {}

func (x *TensorData) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorData.ProtoReflect.Descriptor instead.
func (*TensorData) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{3}
}

func (x *TensorData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TensorData) GetShape() []uint32 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *TensorData) GetDtype() string {
	if x != nil {
		return x.Dtype
	}
	return ""
}

type PlaceholderRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint32                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceholderRange) Reset() {
	*x = PlaceholderRange{}
	mi := &file_vllm_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceholderRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceholderRange) ProtoMessage() {}

func (x *PlaceholderRange) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceholderRange.ProtoReflect.Descriptor instead.
func (*PlaceholderRange) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{4}
}

func (x *PlaceholderRange) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PlaceholderRange) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

// Multimodal inputs for vision/audio models
type MultimodalInputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Preprocessed pixel values tensor
	PixelValues *TensorData `protobuf:"bytes,2,opt,name=pixel_values,json=pixelValues,proto3" json:"pixel_values,omitempty"`
	// Model-specific tensors (image_grid_thw, aspect_ratios, etc.)
	ModelSpecificTensors map[string]*TensorData `protobuf:"bytes,3,rep,name=model_specific_tensors,json=modelSpecificTensors,proto3" json:"model_specific_tensors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Image token ID used for placeholder expansion
	ImTokenId *uint32 `protobuf:"varint,4,opt,name=im_token_id,json=imTokenId,proto3,oneof" json:"im_token_id,omitempty"`
	// Placeholder offsets: where each image's tokens are in input_ids
	MmPlaceholders []*PlaceholderRange `protobuf:"bytes,5,rep,name=mm_placeholders,json=mmPlaceholders,proto3" json:"mm_placeholders,omitempty"`
	// Per-image blake3 hex hashes for encoder output caching
	MmHashes []string `protobuf:"bytes,6,rep,name=mm_hashes,json=mmHashes,proto3" json:"mm_hashes,omitempty"`
	// Tensor keys whose first dimension is per-image (batched).
	// Keys not listed here are shared across all images.
	BatchedKeys []string `protobuf:"bytes,7,rep,name=batched_keys,json=batchedKeys,proto3" json:"batched_keys,omitempty"`
	// Tensor keys that need flat slicing: maps tensor name → sizes tensor name.
	// e.g. {"pixel_values": "patches_per_image"} means pixel_values should be
	// split per-item using sizes from the patches_per_image tensor.
	FlatKeys map[string]string `protobuf:"bytes,8,rep,name=flat_keys,json=flatKeys,proto3" json:"flat_keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Tensor keys that should remain on CPU (not transferred to GPU).
	// Maps to vLLM's MultiModalFieldConfig keep_on_cpu flag.
	KeepOnCpuKeys []string `protobuf:"bytes,9,rep,name=keep_on_cpu_keys,json=keepOnCpuKeys,proto3" json:"keep_on_cpu_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultimodalInputs) Reset() {
	*x = MultimodalInputs{}
	mi := &file_vllm_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultimodalInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultimodalInputs) ProtoMessage() {}

func (x *MultimodalInputs) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultimodalInputs.ProtoReflect.Descriptor instead.
func (*MultimodalInputs) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{5}
}

func (x *MultimodalInputs) GetPixelValues() *TensorData {
	if x != nil {
		return x.PixelValues
	}
	return nil
}

func (x *MultimodalInputs) GetModelSpecificTensors() map[string]*TensorData {
	if x != nil {
		return x.ModelSpecificTensors
	}
	return nil
}

func (x *MultimodalInputs) GetImTokenId() uint32 {
	if x != nil && x.ImTokenId != nil {
		return *x.ImTokenId
	}
	return 0
}

func (x *MultimodalInputs) GetMmPlaceholders() []*PlaceholderRange {
	if x != nil {
		return x.MmPlaceholders
	}
	return nil
}

func (x *MultimodalInputs) GetMmHashes() []string {
	if x != nil {
		return x.MmHashes
	}
	return nil
}

func (x *MultimodalInputs) GetBatchedKeys() []string {
	if x != nil {
		return x.BatchedKeys
	}
	return nil
}

func (x *MultimodalInputs) GetFlatKeys() map[string]string {
	if x != nil {
		return x.FlatKeys
	}
	return nil
}

func (x *MultimodalInputs) GetKeepOnCpuKeys() []string {
	if x != nil {
		return x.KeepOnCpuKeys
	}
	return nil
}

type GenerateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Prompt input
	//
	// Types that are valid to be assigned to Input:
	//
	//	*GenerateRequest_Tokenized
	//	*GenerateRequest_Text
	Input isGenerateRequest_Input `protobuf_oneof:"input"`
	// Generation parameters (includes logprobs config)
	SamplingParams *SamplingParams `protobuf:"bytes,4,opt,name=sampling_params,json=samplingParams,proto3" json:"sampling_params,omitempty"`
	// Streaming
	Stream bool `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`
	// KV transfer parameters for PD disaggregation (Mooncake)
	// Decode worker uses this to fetch KV cache from prefill worker
	KvTransferParams *KvTransferParams `protobuf:"bytes,6,opt,name=kv_transfer_params,json=kvTransferParams,proto3" json:"kv_transfer_params,omitempty"`
	// Optional multimodal data (images for vision models)
	MmInputs      *MultimodalInputs `protobuf:"bytes,7,opt,name=mm_inputs,json=mmInputs,proto3" json:"mm_inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_vllm_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GenerateRequest) GetInput() isGenerateRequest_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *GenerateRequest) GetTokenized() *TokenizedInput {
	if x != nil {
		if x, ok := x.Input.(*GenerateRequest_Tokenized); ok {
			return x.Tokenized
		}
	}
	return nil
}

func (x *GenerateRequest) GetText() string {
	if x != nil {
		if x, ok := x.Input.(*GenerateRequest_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *GenerateRequest) GetSamplingParams() *SamplingParams {
	if x != nil {
		return x.SamplingParams
	}
	return nil
}

func (x *GenerateRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *GenerateRequest) GetKvTransferParams() *KvTransferParams {
	if x != nil {
		return x.KvTransferParams
	}
	return nil
}

func (x *GenerateRequest) GetMmInputs() *MultimodalInputs {
	if x != nil {
		return x.MmInputs
	}
	return nil
}

type isGenerateRequest_Input interface {
	isGenerateRequest_Input()
}

type GenerateRequest_Tokenized struct {
	Tokenized *TokenizedInput `protobuf:"bytes,2,opt,name=tokenized,proto3,oneof"`
}

type GenerateRequest_Text struct {
	Text string `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

func (*GenerateRequest_Tokenized) isGenerateRequest_Input() {}

func (*GenerateRequest_Text) isGenerateRequest_Input() {}

// KV cache transfer parameters for Mooncake PD disaggregation
type KvTransferParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteHost    string                 `protobuf:"bytes,1,opt,name=remote_host,json=remoteHost,proto3" json:"remote_host,omitempty"`  // Prefill worker's side-channel host
	RemotePort    uint32                 `protobuf:"varint,2,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"` // Prefill worker's side-channel port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvTransferParams) Reset() {
	*x = KvTransferParams{}
	mi := &file_vllm_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvTransferParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvTransferParams) ProtoMessage() {}

func (x *KvTransferParams) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvTransferParams.ProtoReflect.Descriptor instead.
func (*KvTransferParams) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{7}
}

func (x *KvTransferParams) GetRemoteHost() string {
	if x != nil {
		return x.RemoteHost
	}
	return ""
}

func (x *KvTransferParams) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

// Output logprobs - matches SGLang structure for code reuse
type OutputLogProbs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenLogprobs []float32              `protobuf:"fixed32,1,rep,packed,name=token_logprobs,json=tokenLogprobs,proto3" json:"token_logprobs,omitempty"` // Logprob for each output token
	TokenIds      []uint32               `protobuf:"varint,2,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`                 // Token ID for each position
	TopLogprobs   []*TopLogProbs         `protobuf:"bytes,3,rep,name=top_logprobs,json=topLogprobs,proto3" json:"top_logprobs,omitempty"`                // Top-k alternatives per position
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputLogProbs) Reset() {
	*x = OutputLogProbs{}
	mi := &file_vllm_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputLogProbs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputLogProbs) ProtoMessage() {}

func (x *OutputLogProbs) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputLogProbs.ProtoReflect.Descriptor instead.
func (*OutputLogProbs) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{8}
}

func (x *OutputLogProbs) GetTokenLogprobs() []float32 {
	if x != nil {
		return x.TokenLogprobs
	}
	return nil
}

func (x *OutputLogProbs) GetTokenIds() []uint32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *OutputLogProbs) GetTopLogprobs() []*TopLogProbs {
	if x != nil {
		return x.TopLogprobs
	}
	return nil
}

// Input (prompt) logprobs - first token has no logprob (None)
type InputLogProbs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenLogprobs []*InputTokenLogProb   `protobuf:"bytes,1,rep,name=token_logprobs,json=tokenLogprobs,proto3" json:"token_logprobs,omitempty"` // Logprob per prompt token
	TokenIds      []uint32               `protobuf:"varint,2,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`        // Prompt token IDs
	TopLogprobs   []*TopLogProbs         `protobuf:"bytes,3,rep,name=top_logprobs,json=topLogprobs,proto3" json:"top_logprobs,omitempty"`       // Top-k alternatives per position
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputLogProbs) Reset() {
	*x = InputLogProbs{}
	mi := &file_vllm_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputLogProbs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputLogProbs) ProtoMessage() {}

func (x *InputLogProbs) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputLogProbs.ProtoReflect.Descriptor instead.
func (*InputLogProbs) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{9}
}

func (x *InputLogProbs) GetTokenLogprobs() []*InputTokenLogProb {
	if x != nil {
		return x.TokenLogprobs
	}
	return nil
}

func (x *InputLogProbs) GetTokenIds() []uint32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *InputLogProbs) GetTopLogprobs() []*TopLogProbs {
	if x != nil {
		return x.TopLogprobs
	}
	return nil
}

// Wrapper for optional logprob (first prompt token has no logprob)
type InputTokenLogProb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *float32               `protobuf:"fixed32,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputTokenLogProb) Reset() {
	*x = InputTokenLogProb{}
	mi := &file_vllm_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputTokenLogProb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputTokenLogProb) ProtoMessage() {}

func (x *InputTokenLogProb) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputTokenLogProb.ProtoReflect.Descriptor instead.
func (*InputTokenLogProb) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{10}
}

func (x *InputTokenLogProb) GetValue() float32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type TopLogProbs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`                    // Logprob values for top-k tokens
	TokenIds      []uint32               `protobuf:"varint,2,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"` // Token IDs for top-k tokens
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopLogProbs) Reset() {
	*x = TopLogProbs{}
	mi := &file_vllm_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopLogProbs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopLogProbs) ProtoMessage() {}

func (x *TopLogProbs) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopLogProbs.ProtoReflect.Descriptor instead.
func (*TopLogProbs) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{11}
}

func (x *TopLogProbs) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *TopLogProbs) GetTokenIds() []uint32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

type GenerateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GenerateResponse_Chunk
	//	*GenerateResponse_Complete
	Response      isGenerateResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_vllm_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateResponse) GetResponse() isGenerateResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GenerateResponse) GetChunk() *GenerateStreamChunk {
	if x != nil {
		if x, ok := x.Response.(*GenerateResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *GenerateResponse) GetComplete() *GenerateComplete {
	if x != nil {
		if x, ok := x.Response.(*GenerateResponse_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

type isGenerateResponse_Response interface {
	isGenerateResponse_Response()
}

type GenerateResponse_Chunk struct {
	Chunk *GenerateStreamChunk `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"` // For streaming
}

type GenerateResponse_Complete struct {
	Complete *GenerateComplete `protobuf:"bytes,2,opt,name=complete,proto3,oneof"` // For final/non-streaming
}

func (*GenerateResponse_Chunk) isGenerateResponse_Response() {}

func (*GenerateResponse_Complete) isGenerateResponse_Response() {}

type GenerateStreamChunk struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TokenIds         []uint32               `protobuf:"varint,1,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"` // Incremental tokens
	PromptTokens     uint32                 `protobuf:"varint,2,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint32                 `protobuf:"varint,3,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	CachedTokens     uint32                 `protobuf:"varint,4,opt,name=cached_tokens,json=cachedTokens,proto3" json:"cached_tokens,omitempty"`
	// Logprobs support
	OutputLogprobs *OutputLogProbs `protobuf:"bytes,5,opt,name=output_logprobs,json=outputLogprobs,proto3" json:"output_logprobs,omitempty"`
	InputLogprobs  *InputLogProbs  `protobuf:"bytes,6,opt,name=input_logprobs,json=inputLogprobs,proto3" json:"input_logprobs,omitempty"` // Only in first chunk
	// Index for n>1 support (0-indexed, identifies which of n outputs this belongs to)
	Index         uint32 `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateStreamChunk) Reset() {
	*x = GenerateStreamChunk{}
	mi := &file_vllm_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateStreamChunk) ProtoMessage() {}

func (x *GenerateStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateStreamChunk.ProtoReflect.Descriptor instead.
func (*GenerateStreamChunk) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateStreamChunk) GetTokenIds() []uint32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *GenerateStreamChunk) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *GenerateStreamChunk) GetCompletionTokens() uint32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *GenerateStreamChunk) GetCachedTokens() uint32 {
	if x != nil {
		return x.CachedTokens
	}
	return 0
}

func (x *GenerateStreamChunk) GetOutputLogprobs() *OutputLogProbs {
	if x != nil {
		return x.OutputLogprobs
	}
	return nil
}

func (x *GenerateStreamChunk) GetInputLogprobs() *InputLogProbs {
	if x != nil {
		return x.InputLogprobs
	}
	return nil
}

func (x *GenerateStreamChunk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type GenerateComplete struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OutputIds        []uint32               `protobuf:"varint,1,rep,packed,name=output_ids,json=outputIds,proto3" json:"output_ids,omitempty"`  // All output tokens
	FinishReason     string                 `protobuf:"bytes,2,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"` // "stop", "length", "abort"
	PromptTokens     uint32                 `protobuf:"varint,3,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint32                 `protobuf:"varint,4,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	CachedTokens     uint32                 `protobuf:"varint,5,opt,name=cached_tokens,json=cachedTokens,proto3" json:"cached_tokens,omitempty"`
	// Logprobs support
	OutputLogprobs *OutputLogProbs `protobuf:"bytes,6,opt,name=output_logprobs,json=outputLogprobs,proto3" json:"output_logprobs,omitempty"`
	InputLogprobs  *InputLogProbs  `protobuf:"bytes,7,opt,name=input_logprobs,json=inputLogprobs,proto3" json:"input_logprobs,omitempty"`
	// Index for n>1 support (0-indexed, identifies which of n outputs this belongs to)
	Index uint32 `protobuf:"varint,8,opt,name=index,proto3" json:"index,omitempty"`
	// KV transfer parameters returned by prefill worker (Mooncake PD)
	// Contains prefill's side-channel address for decode to fetch KV cache
	KvTransferParams *KvTransferParams `protobuf:"bytes,9,opt,name=kv_transfer_params,json=kvTransferParams,proto3" json:"kv_transfer_params,omitempty"`
	// Matched stop information (for stop sequences)
	//
	// Types that are valid to be assigned to MatchedStop:
	//
	//	*GenerateComplete_MatchedTokenId
	//	*GenerateComplete_MatchedStopStr
	MatchedStop   isGenerateComplete_MatchedStop `protobuf_oneof:"matched_stop"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateComplete) Reset() {
	*x = GenerateComplete{}
	mi := &file_vllm_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateComplete) ProtoMessage() {}

func (x *GenerateComplete) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateComplete.ProtoReflect.Descriptor instead.
func (*GenerateComplete) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{14}
}

func (x *GenerateComplete) GetOutputIds() []uint32 {
	if x != nil {
		return x.OutputIds
	}
	return nil
}

func (x *GenerateComplete) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *GenerateComplete) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *GenerateComplete) GetCompletionTokens() uint32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *GenerateComplete) GetCachedTokens() uint32 {
	if x != nil {
		return x.CachedTokens
	}
	return 0
}

func (x *GenerateComplete) GetOutputLogprobs() *OutputLogProbs {
	if x != nil {
		return x.OutputLogprobs
	}
	return nil
}

func (x *GenerateComplete) GetInputLogprobs() *InputLogProbs {
	if x != nil {
		return x.InputLogprobs
	}
	return nil
}

func (x *GenerateComplete) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GenerateComplete) GetKvTransferParams() *KvTransferParams {
	if x != nil {
		return x.KvTransferParams
	}
	return nil
}

func (x *GenerateComplete) GetMatchedStop() isGenerateComplete_MatchedStop {
	if x != nil {
		return x.MatchedStop
	}
	return nil
}

func (x *GenerateComplete) GetMatchedTokenId() uint32 {
	if x != nil {
		if x, ok := x.MatchedStop.(*GenerateComplete_MatchedTokenId); ok {
			return x.MatchedTokenId
		}
	}
	return 0
}

func (x *GenerateComplete) GetMatchedStopStr() string {
	if x != nil {
		if x, ok := x.MatchedStop.(*GenerateComplete_MatchedStopStr); ok {
			return x.MatchedStopStr
		}
	}
	return ""
}

type isGenerateComplete_MatchedStop interface {
	isGenerateComplete_MatchedStop()
}

type GenerateComplete_MatchedTokenId struct {
	MatchedTokenId uint32 `protobuf:"varint,10,opt,name=matched_token_id,json=matchedTokenId,proto3,oneof"`
}

type GenerateComplete_MatchedStopStr struct {
	MatchedStopStr string `protobuf:"bytes,11,opt,name=matched_stop_str,json=matchedStopStr,proto3,oneof"`
}

func (*GenerateComplete_MatchedTokenId) isGenerateComplete_MatchedStop() {}

func (*GenerateComplete_MatchedStopStr) isGenerateComplete_MatchedStop() {}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Tokenized     *TokenizedInput        `protobuf:"bytes,2,opt,name=tokenized,proto3" json:"tokenized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_vllm_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{15}
}

func (x *EmbedRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EmbedRequest) GetTokenized() *TokenizedInput {
	if x != nil {
		return x.Tokenized
	}
	return nil
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	PromptTokens  uint32                 `protobuf:"varint,2,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	EmbeddingDim  uint32                 `protobuf:"varint,3,opt,name=embedding_dim,json=embeddingDim,proto3" json:"embedding_dim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_vllm_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{16}
}

func (x *EmbedResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbedResponse) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *EmbedResponse) GetEmbeddingDim() uint32 {
	if x != nil {
		return x.EmbeddingDim
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_vllm_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{17}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_vllm_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{18}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestIds    []string               `protobuf:"bytes,1,rep,name=request_ids,json=requestIds,proto3" json:"request_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_vllm_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{19}
}

func (x *AbortRequest) GetRequestIds() []string {
	if x != nil {
		return x.RequestIds
	}
	return nil
}

type AbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortResponse) Reset() {
	*x = AbortResponse{}
	mi := &file_vllm_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResponse) ProtoMessage() {}

func (x *AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResponse.ProtoReflect.Descriptor instead.
func (*AbortResponse) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{20}
}

type GetModelInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelInfoRequest) Reset() {
	*x = GetModelInfoRequest{}
	mi := &file_vllm_engine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelInfoRequest) ProtoMessage() {}

func (x *GetModelInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelInfoRequest.ProtoReflect.Descriptor instead.
func (*GetModelInfoRequest) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{21}
}

type GetModelInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModelPath        string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	IsGeneration     bool                   `protobuf:"varint,2,opt,name=is_generation,json=isGeneration,proto3" json:"is_generation,omitempty"`
	MaxContextLength uint32                 `protobuf:"varint,3,opt,name=max_context_length,json=maxContextLength,proto3" json:"max_context_length,omitempty"`
	VocabSize        uint32                 `protobuf:"varint,4,opt,name=vocab_size,json=vocabSize,proto3" json:"vocab_size,omitempty"`
	SupportsVision   bool                   `protobuf:"varint,5,opt,name=supports_vision,json=supportsVision,proto3" json:"supports_vision,omitempty"`
	ServedModelName  string                 `protobuf:"bytes,6,opt,name=served_model_name,json=servedModelName,proto3" json:"served_model_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetModelInfoResponse) Reset() {
	*x = GetModelInfoResponse{}
	mi := &file_vllm_engine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelInfoResponse) ProtoMessage() {}

func (x *GetModelInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelInfoResponse.ProtoReflect.Descriptor instead.
func (*GetModelInfoResponse) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{22}
}

func (x *GetModelInfoResponse) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *GetModelInfoResponse) GetIsGeneration() bool {
	if x != nil {
		return x.IsGeneration
	}
	return false
}

func (x *GetModelInfoResponse) GetMaxContextLength() uint32 {
	if x != nil {
		return x.MaxContextLength
	}
	return 0
}

func (x *GetModelInfoResponse) GetVocabSize() uint32 {
	if x != nil {
		return x.VocabSize
	}
	return 0
}

func (x *GetModelInfoResponse) GetSupportsVision() bool {
	if x != nil {
		return x.SupportsVision
	}
	return false
}

func (x *GetModelInfoResponse) GetServedModelName() string {
	if x != nil {
		return x.ServedModelName
	}
	return ""
}

type GetServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	mi := &file_vllm_engine_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{23}
}

type GetServerInfoResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActiveRequests       uint32                 `protobuf:"varint,1,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"`
	IsPaused             bool                   `protobuf:"varint,2,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`
	LastReceiveTimestamp float64                `protobuf:"fixed64,3,opt,name=last_receive_timestamp,json=lastReceiveTimestamp,proto3" json:"last_receive_timestamp,omitempty"`
	UptimeSeconds        float64                `protobuf:"fixed64,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ServerType           string                 `protobuf:"bytes,5,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"` // "vllm-grpc"
	// KV transfer config (for PD disaggregation)
	KvConnector   string `protobuf:"bytes,6,opt,name=kv_connector,json=kvConnector,proto3" json:"kv_connector,omitempty"` // "MooncakeConnector", "NixlConnector", "" if not configured
	KvRole        string `protobuf:"bytes,7,opt,name=kv_role,json=kvRole,proto3" json:"kv_role,omitempty"`                // "kv_producer", "kv_consumer", "kv_both", "" if not configured
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoResponse) Reset() {
	*x = GetServerInfoResponse{}
	mi := &file_vllm_engine_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoResponse) ProtoMessage() {}

func (x *GetServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vllm_engine_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_vllm_engine_proto_rawDescGZIP(), []int{24}
}

func (x *GetServerInfoResponse) GetActiveRequests() uint32 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

func (x *GetServerInfoResponse) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

func (x *GetServerInfoResponse) GetLastReceiveTimestamp() float64 {
	if x != nil {
		return x.LastReceiveTimestamp
	}
	return 0
}

func (x *GetServerInfoResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetServerInfoResponse) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

func (x *GetServerInfoResponse) GetKvConnector() string {
	if x != nil {
		return x.KvConnector
	}
	return ""
}

func (x *GetServerInfoResponse) GetKvRole() string {
	if x != nil {
		return x.KvRole
	}
	return ""
}

var File_vllm_engine_proto protoreflect.FileDescriptor

const file_vllm_engine_proto_rawDesc = "" +
	"\n" +
	"\x11vllm_engine.proto\x12\x10vllm.grpc.engine\x1a\fcommon.proto\"\xda\t\n" +
	"\x0eSamplingParams\x12%\n" +
	"\vtemperature\x18\x01 \x01(\x02H\x01R\vtemperature\x88\x01\x01\x12\x13\n" +
	"\x05top_p\x18\x02 \x01(\x02R\x04topP\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\x12\x13\n" +
	"\x05min_p\x18\x04 \x01(\x02R\x04minP\x12+\n" +
	"\x11frequency_penalty\x18\x05 \x01(\x02R\x10frequencyPenalty\x12)\n" +
	"\x10presence_penalty\x18\x06 \x01(\x02R\x0fpresencePenalty\x12-\n" +
	"\x12repetition_penalty\x18\a \x01(\x02R\x11repetitionPenalty\x12\"\n" +
	"\n" +
	"max_tokens\x18\b \x01(\rH\x02R\tmaxTokens\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"min_tokens\x18\t \x01(\rR\tminTokens\x12\x12\n" +
	"\x04stop\x18\n" +
	" \x03(\tR\x04stop\x12$\n" +
	"\x0estop_token_ids\x18\v \x03(\rR\fstopTokenIds\x12.\n" +
	"\x13skip_special_tokens\x18\f \x01(\bR\x11skipSpecialTokens\x12A\n" +
	"\x1dspaces_between_special_tokens\x18\r \x01(\bR\x1aspacesBetweenSpecialTokens\x12\x1d\n" +
	"\n" +
	"ignore_eos\x18\x0e \x01(\bR\tignoreEos\x12\f\n" +
	"\x01n\x18\x0f \x01(\rR\x01n\x12\x1f\n" +
	"\blogprobs\x18\x16 \x01(\x05H\x03R\blogprobs\x88\x01\x01\x12,\n" +
	"\x0fprompt_logprobs\x18\x17 \x01(\x05H\x04R\x0epromptLogprobs\x88\x01\x01\x12\x17\n" +
	"\x04seed\x18\x18 \x01(\x05H\x05R\x04seed\x88\x01\x01\x12:\n" +
	"\x1ainclude_stop_str_in_output\x18\x19 \x01(\bR\x16includeStopStrInOutput\x12N\n" +
	"\n" +
	"logit_bias\x18\x1a \x03(\v2/.vllm.grpc.engine.SamplingParams.LogitBiasEntryR\tlogitBias\x129\n" +
	"\x16truncate_prompt_tokens\x18\x1b \x01(\x05H\x06R\x14truncatePromptTokens\x88\x01\x01\x12!\n" +
	"\vjson_schema\x18\x10 \x01(\tH\x00R\n" +
	"jsonSchema\x12\x16\n" +
	"\x05regex\x18\x11 \x01(\tH\x00R\x05regex\x12\x1a\n" +
	"\agrammar\x18\x12 \x01(\tH\x00R\agrammar\x12'\n" +
	"\x0estructural_tag\x18\x13 \x01(\tH\x00R\rstructuralTag\x12!\n" +
	"\vjson_object\x18\x14 \x01(\bH\x00R\n" +
	"jsonObject\x12<\n" +
	"\x06choice\x18\x15 \x01(\v2\".vllm.grpc.engine.ChoiceConstraintH\x00R\x06choice\x1a<\n" +
	"\x0eLogitBiasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01B\f\n" +
	"\n" +
	"constraintB\x0e\n" +
	"\f_temperatureB\r\n" +
	"\v_max_tokensB\v\n" +
	"\t_logprobsB\x12\n" +
	"\x10_prompt_logprobsB\a\n" +
	"\x05_seedB\x19\n" +
	"\x17_truncate_prompt_tokens\",\n" +
	"\x10ChoiceConstraint\x12\x18\n" +
	"\achoices\x18\x01 \x03(\tR\achoices\"R\n" +
	"\x0eTokenizedInput\x12#\n" +
	"\roriginal_text\x18\x01 \x01(\tR\foriginalText\x12\x1b\n" +
	"\tinput_ids\x18\x02 \x03(\rR\binputIds\"L\n" +
	"\n" +
	"TensorData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05shape\x18\x02 \x03(\rR\x05shape\x12\x14\n" +
	"\x05dtype\x18\x03 \x01(\tR\x05dtype\"B\n" +
	"\x10PlaceholderRange\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\rR\x06length\"\xab\x05\n" +
	"\x10MultimodalInputs\x12?\n" +
	"\fpixel_values\x18\x02 \x01(\v2\x1c.vllm.grpc.engine.TensorDataR\vpixelValues\x12r\n" +
	"\x16model_specific_tensors\x18\x03 \x03(\v2<.vllm.grpc.engine.MultimodalInputs.ModelSpecificTensorsEntryR\x14modelSpecificTensors\x12#\n" +
	"\vim_token_id\x18\x04 \x01(\rH\x00R\timTokenId\x88\x01\x01\x12K\n" +
	"\x0fmm_placeholders\x18\x05 \x03(\v2\".vllm.grpc.engine.PlaceholderRangeR\x0emmPlaceholders\x12\x1b\n" +
	"\tmm_hashes\x18\x06 \x03(\tR\bmmHashes\x12!\n" +
	"\fbatched_keys\x18\a \x03(\tR\vbatchedKeys\x12M\n" +
	"\tflat_keys\x18\b \x03(\v20.vllm.grpc.engine.MultimodalInputs.FlatKeysEntryR\bflatKeys\x12'\n" +
	"\x10keep_on_cpu_keys\x18\t \x03(\tR\rkeepOnCpuKeys\x1ae\n" +
	"\x19ModelSpecificTensorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.vllm.grpc.engine.TensorDataR\x05value:\x028\x01\x1a;\n" +
	"\rFlatKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_im_token_idJ\x04\b\x01\x10\x02\"\x87\x03\n" +
	"\x0fGenerateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12@\n" +
	"\ttokenized\x18\x02 \x01(\v2 .vllm.grpc.engine.TokenizedInputH\x00R\ttokenized\x12\x14\n" +
	"\x04text\x18\x03 \x01(\tH\x00R\x04text\x12I\n" +
	"\x0fsampling_params\x18\x04 \x01(\v2 .vllm.grpc.engine.SamplingParamsR\x0esamplingParams\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\x12P\n" +
	"\x12kv_transfer_params\x18\x06 \x01(\v2\".vllm.grpc.engine.KvTransferParamsR\x10kvTransferParams\x12?\n" +
	"\tmm_inputs\x18\a \x01(\v2\".vllm.grpc.engine.MultimodalInputsR\bmmInputsB\a\n" +
	"\x05input\"T\n" +
	"\x10KvTransferParams\x12\x1f\n" +
	"\vremote_host\x18\x01 \x01(\tR\n" +
	"remoteHost\x12\x1f\n" +
	"\vremote_port\x18\x02 \x01(\rR\n" +
	"remotePort\"\x96\x01\n" +
	"\x0eOutputLogProbs\x12%\n" +
	"\x0etoken_logprobs\x18\x01 \x03(\x02R\rtokenLogprobs\x12\x1b\n" +
	"\ttoken_ids\x18\x02 \x03(\rR\btokenIds\x12@\n" +
	"\ftop_logprobs\x18\x03 \x03(\v2\x1d.vllm.grpc.engine.TopLogProbsR\vtopLogprobs\"\xba\x01\n" +
	"\rInputLogProbs\x12J\n" +
	"\x0etoken_logprobs\x18\x01 \x03(\v2#.vllm.grpc.engine.InputTokenLogProbR\rtokenLogprobs\x12\x1b\n" +
	"\ttoken_ids\x18\x02 \x03(\rR\btokenIds\x12@\n" +
	"\ftop_logprobs\x18\x03 \x03(\v2\x1d.vllm.grpc.engine.TopLogProbsR\vtopLogprobs\"8\n" +
	"\x11InputTokenLogProb\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x02H\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"B\n" +
	"\vTopLogProbs\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x1b\n" +
	"\ttoken_ids\x18\x02 \x03(\rR\btokenIds\"\x9f\x01\n" +
	"\x10GenerateResponse\x12=\n" +
	"\x05chunk\x18\x01 \x01(\v2%.vllm.grpc.engine.GenerateStreamChunkH\x00R\x05chunk\x12@\n" +
	"\bcomplete\x18\x02 \x01(\v2\".vllm.grpc.engine.GenerateCompleteH\x00R\bcompleteB\n" +
	"\n" +
	"\bresponse\"\xd2\x02\n" +
	"\x13GenerateStreamChunk\x12\x1b\n" +
	"\ttoken_ids\x18\x01 \x03(\rR\btokenIds\x12#\n" +
	"\rprompt_tokens\x18\x02 \x01(\rR\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x03 \x01(\rR\x10completionTokens\x12#\n" +
	"\rcached_tokens\x18\x04 \x01(\rR\fcachedTokens\x12I\n" +
	"\x0foutput_logprobs\x18\x05 \x01(\v2 .vllm.grpc.engine.OutputLogProbsR\x0eoutputLogprobs\x12F\n" +
	"\x0einput_logprobs\x18\x06 \x01(\v2\x1f.vllm.grpc.engine.InputLogProbsR\rinputLogprobs\x12\x14\n" +
	"\x05index\x18\a \x01(\rR\x05index\"\xb0\x04\n" +
	"\x10GenerateComplete\x12\x1d\n" +
	"\n" +
	"output_ids\x18\x01 \x03(\rR\toutputIds\x12#\n" +
	"\rfinish_reason\x18\x02 \x01(\tR\ffinishReason\x12#\n" +
	"\rprompt_tokens\x18\x03 \x01(\rR\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x04 \x01(\rR\x10completionTokens\x12#\n" +
	"\rcached_tokens\x18\x05 \x01(\rR\fcachedTokens\x12I\n" +
	"\x0foutput_logprobs\x18\x06 \x01(\v2 .vllm.grpc.engine.OutputLogProbsR\x0eoutputLogprobs\x12F\n" +
	"\x0einput_logprobs\x18\a \x01(\v2\x1f.vllm.grpc.engine.InputLogProbsR\rinputLogprobs\x12\x14\n" +
	"\x05index\x18\b \x01(\rR\x05index\x12P\n" +
	"\x12kv_transfer_params\x18\t \x01(\v2\".vllm.grpc.engine.KvTransferParamsR\x10kvTransferParams\x12*\n" +
	"\x10matched_token_id\x18\n" +
	" \x01(\rH\x00R\x0ematchedTokenId\x12*\n" +
	"\x10matched_stop_str\x18\v \x01(\tH\x00R\x0ematchedStopStrB\x0e\n" +
	"\fmatched_stop\"m\n" +
	"\fEmbedRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12>\n" +
	"\ttokenized\x18\x02 \x01(\v2 .vllm.grpc.engine.TokenizedInputR\ttokenized\"w\n" +
	"\rEmbedResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12#\n" +
	"\rprompt_tokens\x18\x02 \x01(\rR\fpromptTokens\x12#\n" +
	"\rembedding_dim\x18\x03 \x01(\rR\fembeddingDim\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\fAbortRequest\x12\x1f\n" +
	"\vrequest_ids\x18\x01 \x03(\tR\n" +
	"requestIds\"\x0f\n" +
	"\rAbortResponse\"\x15\n" +
	"\x13GetModelInfoRequest\"\xfc\x01\n" +
	"\x14GetModelInfoResponse\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\x12#\n" +
	"\ris_generation\x18\x02 \x01(\bR\fisGeneration\x12,\n" +
	"\x12max_context_length\x18\x03 \x01(\rR\x10maxContextLength\x12\x1d\n" +
	"\n" +
	"vocab_size\x18\x04 \x01(\rR\tvocabSize\x12'\n" +
	"\x0fsupports_vision\x18\x05 \x01(\bR\x0esupportsVision\x12*\n" +
	"\x11served_model_name\x18\x06 \x01(\tR\x0fservedModelName\"\x16\n" +
	"\x14GetServerInfoRequest\"\x97\x02\n" +
	"\x15GetServerInfoResponse\x12'\n" +
	"\x0factive_requests\x18\x01 \x01(\rR\x0eactiveRequests\x12\x1b\n" +
	"\tis_paused\x18\x02 \x01(\bR\bisPaused\x124\n" +
	"\x16last_receive_timestamp\x18\x03 \x01(\x01R\x14lastReceiveTimestamp\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x01R\ruptimeSeconds\x12\x1f\n" +
	"\vserver_type\x18\x05 \x01(\tR\n" +
	"serverType\x12!\n" +
	"\fkv_connector\x18\x06 \x01(\tR\vkvConnector\x12\x17\n" +
	"\akv_role\x18\a \x01(\tR\x06kvRole2\xcf\x05\n" +
	"\n" +
	"VllmEngine\x12S\n" +
	"\bGenerate\x12!.vllm.grpc.engine.GenerateRequest\x1a\".vllm.grpc.engine.GenerateResponse0\x01\x12H\n" +
	"\x05Embed\x12\x1e.vllm.grpc.engine.EmbedRequest\x1a\x1f.vllm.grpc.engine.EmbedResponse\x12Z\n" +
	"\vHealthCheck\x12$.vllm.grpc.engine.HealthCheckRequest\x1a%.vllm.grpc.engine.HealthCheckResponse\x12H\n" +
	"\x05Abort\x12\x1e.vllm.grpc.engine.AbortRequest\x1a\x1f.vllm.grpc.engine.AbortResponse\x12]\n" +
	"\fGetModelInfo\x12%.vllm.grpc.engine.GetModelInfoRequest\x1a&.vllm.grpc.engine.GetModelInfoResponse\x12`\n" +
	"\rGetServerInfo\x12&.vllm.grpc.engine.GetServerInfoRequest\x1a'.vllm.grpc.engine.GetServerInfoResponse\x12Z\n" +
	"\fGetTokenizer\x12$.smg.grpc.common.GetTokenizerRequest\x1a\".smg.grpc.common.GetTokenizerChunk0\x01\x12_\n" +
	"\x11SubscribeKvEvents\x12).smg.grpc.common.SubscribeKvEventsRequest\x1a\x1d.smg.grpc.common.KvEventBatch0\x01b\x06proto3"

var (
	file_vllm_engine_proto_rawDescOnce sync.Once
	file_vllm_engine_proto_rawDescData []byte
)

func file_vllm_engine_proto_rawDescGZIP() []byte {
	file_vllm_engine_proto_rawDescOnce.Do(func() {
		file_vllm_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vllm_engine_proto_rawDesc), len(file_vllm_engine_proto_rawDesc)))
	})
	return file_vllm_engine_proto_rawDescData
}

var file_vllm_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_vllm_engine_proto_goTypes = []any{
	(*SamplingParams)(nil),                  // 0: vllm.grpc.engine.SamplingParams
	(*ChoiceConstraint)(nil),                // 1: vllm.grpc.engine.ChoiceConstraint
	(*TokenizedInput)(nil),                  // 2: vllm.grpc.engine.TokenizedInput
	(*TensorData)(nil),                      // 3: vllm.grpc.engine.TensorData
	(*PlaceholderRange)(nil),                // 4: vllm.grpc.engine.PlaceholderRange
	(*MultimodalInputs)(nil),                // 5: vllm.grpc.engine.MultimodalInputs
	(*GenerateRequest)(nil),                 // 6: vllm.grpc.engine.GenerateRequest
	(*KvTransferParams)(nil),                // 7: vllm.grpc.engine.KvTransferParams
	(*OutputLogProbs)(nil),                  // 8: vllm.grpc.engine.OutputLogProbs
	(*InputLogProbs)(nil),                   // 9: vllm.grpc.engine.InputLogProbs
	(*InputTokenLogProb)(nil),               // 10: vllm.grpc.engine.InputTokenLogProb
	(*TopLogProbs)(nil),                     // 11: vllm.grpc.engine.TopLogProbs
	(*GenerateResponse)(nil),                // 12: vllm.grpc.engine.GenerateResponse
	(*GenerateStreamChunk)(nil),             // 13: vllm.grpc.engine.GenerateStreamChunk
	(*GenerateComplete)(nil),                // 14: vllm.grpc.engine.GenerateComplete
	(*EmbedRequest)(nil),                    // 15: vllm.grpc.engine.EmbedRequest
	(*EmbedResponse)(nil),                   // 16: vllm.grpc.engine.EmbedResponse
	(*HealthCheckRequest)(nil),              // 17: vllm.grpc.engine.HealthCheckRequest
	(*HealthCheckResponse)(nil),             // 18: vllm.grpc.engine.HealthCheckResponse
	(*AbortRequest)(nil),                    // 19: vllm.grpc.engine.AbortRequest
	(*AbortResponse)(nil),                   // 20: vllm.grpc.engine.AbortResponse
	(*GetModelInfoRequest)(nil),             // 21: vllm.grpc.engine.GetModelInfoRequest
	(*GetModelInfoResponse)(nil),            // 22: vllm.grpc.engine.GetModelInfoResponse
	(*GetServerInfoRequest)(nil),            // 23: vllm.grpc.engine.GetServerInfoRequest
	(*GetServerInfoResponse)(nil),           // 24: vllm.grpc.engine.GetServerInfoResponse
	nil,                                     // 25: vllm.grpc.engine.SamplingParams.LogitBiasEntry
	nil,                                     // 26: vllm.grpc.engine.MultimodalInputs.ModelSpecificTensorsEntry
	nil,                                     // 27: vllm.grpc.engine.MultimodalInputs.FlatKeysEntry
	(*common.GetTokenizerRequest)(nil),      // 28: smg.grpc.common.GetTokenizerRequest
	(*common.SubscribeKvEventsRequest)(nil), // 29: smg.grpc.common.SubscribeKvEventsRequest
	(*common.GetTokenizerChunk)(nil),        // 30: smg.grpc.common.GetTokenizerChunk
	(*common.KvEventBatch)(nil),             // 31: smg.grpc.common.KvEventBatch
}
var file_vllm_engine_proto_depIdxs = []int32{
	25, // 0: vllm.grpc.engine.SamplingParams.logit_bias:type_name -> vllm.grpc.engine.SamplingParams.LogitBiasEntry
	1,  // 1: vllm.grpc.engine.SamplingParams.choice:type_name -> vllm.grpc.engine.ChoiceConstraint
	3,  // 2: vllm.grpc.engine.MultimodalInputs.pixel_values:type_name -> vllm.grpc.engine.TensorData
	26, // 3: vllm.grpc.engine.MultimodalInputs.model_specific_tensors:type_name -> vllm.grpc.engine.MultimodalInputs.ModelSpecificTensorsEntry
	4,  // 4: vllm.grpc.engine.MultimodalInputs.mm_placeholders:type_name -> vllm.grpc.engine.PlaceholderRange
	27, // 5: vllm.grpc.engine.MultimodalInputs.flat_keys:type_name -> vllm.grpc.engine.MultimodalInputs.FlatKeysEntry
	2,  // 6: vllm.grpc.engine.GenerateRequest.tokenized:type_name -> vllm.grpc.engine.TokenizedInput
	0,  // 7: vllm.grpc.engine.GenerateRequest.sampling_params:type_name -> vllm.grpc.engine.SamplingParams
	7,  // 8: vllm.grpc.engine.GenerateRequest.kv_transfer_params:type_name -> vllm.grpc.engine.KvTransferParams
	5,  // 9: vllm.grpc.engine.GenerateRequest.mm_inputs:type_name -> vllm.grpc.engine.MultimodalInputs
	11, // 10: vllm.grpc.engine.OutputLogProbs.top_logprobs:type_name -> vllm.grpc.engine.TopLogProbs
	10, // 11: vllm.grpc.engine.InputLogProbs.token_logprobs:type_name -> vllm.grpc.engine.InputTokenLogProb
	11, // 12: vllm.grpc.engine.InputLogProbs.top_logprobs:type_name -> vllm.grpc.engine.TopLogProbs
	13, // 13: vllm.grpc.engine.GenerateResponse.chunk:type_name -> vllm.grpc.engine.GenerateStreamChunk
	14, // 14: vllm.grpc.engine.GenerateResponse.complete:type_name -> vllm.grpc.engine.GenerateComplete
	8,  // 15: vllm.grpc.engine.GenerateStreamChunk.output_logprobs:type_name -> vllm.grpc.engine.OutputLogProbs
	9,  // 16: vllm.grpc.engine.GenerateStreamChunk.input_logprobs:type_name -> vllm.grpc.engine.InputLogProbs
	8,  // 17: vllm.grpc.engine.GenerateComplete.output_logprobs:type_name -> vllm.grpc.engine.OutputLogProbs
	9,  // 18: vllm.grpc.engine.GenerateComplete.input_logprobs:type_name -> vllm.grpc.engine.InputLogProbs
	7,  // 19: vllm.grpc.engine.GenerateComplete.kv_transfer_params:type_name -> vllm.grpc.engine.KvTransferParams
	2,  // 20: vllm.grpc.engine.EmbedRequest.tokenized:type_name -> vllm.grpc.engine.TokenizedInput
	3,  // 21: vllm.grpc.engine.MultimodalInputs.ModelSpecificTensorsEntry.value:type_name -> vllm.grpc.engine.TensorData
	6,  // 22: vllm.grpc.engine.VllmEngine.Generate:input_type -> vllm.grpc.engine.GenerateRequest
	15, // 23: vllm.grpc.engine.VllmEngine.Embed:input_type -> vllm.grpc.engine.EmbedRequest
	17, // 24: vllm.grpc.engine.VllmEngine.HealthCheck:input_type -> vllm.grpc.engine.HealthCheckRequest
	19, // 25: vllm.grpc.engine.VllmEngine.Abort:input_type -> vllm.grpc.engine.AbortRequest
	21, // 26: vllm.grpc.engine.VllmEngine.GetModelInfo:input_type -> vllm.grpc.engine.GetModelInfoRequest
	23, // 27: vllm.grpc.engine.VllmEngine.GetServerInfo:input_type -> vllm.grpc.engine.GetServerInfoRequest
	28, // 28: vllm.grpc.engine.VllmEngine.GetTokenizer:input_type -> smg.grpc.common.GetTokenizerRequest
	29, // 29: vllm.grpc.engine.VllmEngine.SubscribeKvEvents:input_type -> smg.grpc.common.SubscribeKvEventsRequest
	12, // 30: vllm.grpc.engine.VllmEngine.Generate:output_type -> vllm.grpc.engine.GenerateResponse
	16, // 31: vllm.grpc.engine.VllmEngine.Embed:output_type -> vllm.grpc.engine.EmbedResponse
	18, // 32: vllm.grpc.engine.VllmEngine.HealthCheck:output_type -> vllm.grpc.engine.HealthCheckResponse
	20, // 33: vllm.grpc.engine.VllmEngine.Abort:output_type -> vllm.grpc.engine.AbortResponse
	22, // 34: vllm.grpc.engine.VllmEngine.GetModelInfo:output_type -> vllm.grpc.engine.GetModelInfoResponse
	24, // 35: vllm.grpc.engine.VllmEngine.GetServerInfo:output_type -> vllm.grpc.engine.GetServerInfoResponse
	30, // 36: vllm.grpc.engine.VllmEngine.GetTokenizer:output_type -> smg.grpc.common.GetTokenizerChunk
	31, // 37: vllm.grpc.engine.VllmEngine.SubscribeKvEvents:output_type -> smg.grpc.common.KvEventBatch
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_vllm_engine_proto_init() }
func file_vllm_engine_proto_init() {
	if File_vllm_engine_proto != nil {
		return
	}
	file_vllm_engine_proto_msgTypes[0].OneofWrappers = []any{
		(*SamplingParams_JsonSchema)(nil),
		(*SamplingParams_Regex)(nil),
		(*SamplingParams_Grammar)(nil),
		(*SamplingParams_StructuralTag)(nil),
		(*SamplingParams_JsonObject)(nil),
		(*SamplingParams_Choice)(nil),
	}
	file_vllm_engine_proto_msgTypes[5].OneofWrappers = []any{}
	file_vllm_engine_proto_msgTypes[6].OneofWrappers = []any{
		(*GenerateRequest_Tokenized)(nil),
		(*GenerateRequest_Text)(nil),
	}
	file_vllm_engine_proto_msgTypes[10].OneofWrappers = []any{}
	file_vllm_engine_proto_msgTypes[12].OneofWrappers = []any{
		(*GenerateResponse_Chunk)(nil),
		(*GenerateResponse_Complete)(nil),
	}
	file_vllm_engine_proto_msgTypes[14].OneofWrappers = []any{
		(*GenerateComplete_MatchedTokenId)(nil),
		(*GenerateComplete_MatchedStopStr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vllm_engine_proto_rawDesc), len(file_vllm_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vllm_engine_proto_goTypes,
		DependencyIndexes: file_vllm_engine_proto_depIdxs,
		MessageInfos:      file_vllm_engine_proto_msgTypes,
	}.Build()
	File_vllm_engine_proto = out.File
	file_vllm_engine_proto_goTypes = nil
	file_vllm_engine_proto_depIdxs = nil
}
