// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: vllm_engine.proto

package vllm_engine

import (
	context "context"
	common "github.com/lightseekorg/smg/crates/grpc_client/golang/smg_grpc_proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VllmEngine_Generate_FullMethodName          = "/vllm.grpc.engine.VllmEngine/Generate"
	VllmEngine_Embed_FullMethodName             = "/vllm.grpc.engine.VllmEngine/Embed"
	VllmEngine_HealthCheck_FullMethodName       = "/vllm.grpc.engine.VllmEngine/HealthCheck"
	VllmEngine_Abort_FullMethodName             = "/vllm.grpc.engine.VllmEngine/Abort"
	VllmEngine_GetModelInfo_FullMethodName      = "/vllm.grpc.engine.VllmEngine/GetModelInfo"
	VllmEngine_GetServerInfo_FullMethodName     = "/vllm.grpc.engine.VllmEngine/GetServerInfo"
	VllmEngine_GetTokenizer_FullMethodName      = "/vllm.grpc.engine.VllmEngine/GetTokenizer"
	VllmEngine_SubscribeKvEvents_FullMethodName = "/vllm.grpc.engine.VllmEngine/SubscribeKvEvents"
)

// VllmEngineClient is the client API for VllmEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for vLLM engine communication
// This protocol is designed for efficient binary communication between
// the Rust router and vLLM Python engine (AsyncLLM).
type VllmEngineClient interface {
	// Submit a generation request (supports streaming)
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error)
	// Submit an embedding request
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Abort a running request
	Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortResponse, error)
	// Get model information
	GetModelInfo(ctx context.Context, in *GetModelInfoRequest, opts ...grpc.CallOption) (*GetModelInfoResponse, error)
	// Get server information
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error)
	// Get tokenizer artifacts for remote construction
	GetTokenizer(ctx context.Context, in *common.GetTokenizerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.GetTokenizerChunk], error)
	// Subscribe to KV cache events (server-streaming)
	SubscribeKvEvents(ctx context.Context, in *common.SubscribeKvEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.KvEventBatch], error)
}

type vllmEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewVllmEngineClient(cc grpc.ClientConnInterface) VllmEngineClient {
	return &vllmEngineClient{cc}
}

func (c *vllmEngineClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VllmEngine_ServiceDesc.Streams[0], VllmEngine_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VllmEngine_GenerateClient = grpc.ServerStreamingClient[GenerateResponse]

func (c *vllmEngineClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, VllmEngine_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vllmEngineClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, VllmEngine_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vllmEngineClient) Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortResponse)
	err := c.cc.Invoke(ctx, VllmEngine_Abort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vllmEngineClient) GetModelInfo(ctx context.Context, in *GetModelInfoRequest, opts ...grpc.CallOption) (*GetModelInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelInfoResponse)
	err := c.cc.Invoke(ctx, VllmEngine_GetModelInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vllmEngineClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerInfoResponse)
	err := c.cc.Invoke(ctx, VllmEngine_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vllmEngineClient) GetTokenizer(ctx context.Context, in *common.GetTokenizerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.GetTokenizerChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VllmEngine_ServiceDesc.Streams[1], VllmEngine_GetTokenizer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[common.GetTokenizerRequest, common.GetTokenizerChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VllmEngine_GetTokenizerClient = grpc.ServerStreamingClient[common.GetTokenizerChunk]

func (c *vllmEngineClient) SubscribeKvEvents(ctx context.Context, in *common.SubscribeKvEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.KvEventBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VllmEngine_ServiceDesc.Streams[2], VllmEngine_SubscribeKvEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[common.SubscribeKvEventsRequest, common.KvEventBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VllmEngine_SubscribeKvEventsClient = grpc.ServerStreamingClient[common.KvEventBatch]

// VllmEngineServer is the server API for VllmEngine service.
// All implementations must embed UnimplementedVllmEngineServer
// for forward compatibility.
//
// Service definition for vLLM engine communication
// This protocol is designed for efficient binary communication between
// the Rust router and vLLM Python engine (AsyncLLM).
type VllmEngineServer interface {
	// Submit a generation request (supports streaming)
	Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error
	// Submit an embedding request
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Abort a running request
	Abort(context.Context, *AbortRequest) (*AbortResponse, error)
	// Get model information
	GetModelInfo(context.Context, *GetModelInfoRequest) (*GetModelInfoResponse, error)
	// Get server information
	GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error)
	// Get tokenizer artifacts for remote construction
	GetTokenizer(*common.GetTokenizerRequest, grpc.ServerStreamingServer[common.GetTokenizerChunk]) error
	// Subscribe to KV cache events (server-streaming)
	SubscribeKvEvents(*common.SubscribeKvEventsRequest, grpc.ServerStreamingServer[common.KvEventBatch]) error
	mustEmbedUnimplementedVllmEngineServer()
}

// UnimplementedVllmEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVllmEngineServer struct{}

func (UnimplementedVllmEngineServer) Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedVllmEngineServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedVllmEngineServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedVllmEngineServer) Abort(context.Context, *AbortRequest) (*AbortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedVllmEngineServer) GetModelInfo(context.Context, *GetModelInfoRequest) (*GetModelInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelInfo not implemented")
}
func (UnimplementedVllmEngineServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedVllmEngineServer) GetTokenizer(*common.GetTokenizerRequest, grpc.ServerStreamingServer[common.GetTokenizerChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetTokenizer not implemented")
}
func (UnimplementedVllmEngineServer) SubscribeKvEvents(*common.SubscribeKvEventsRequest, grpc.ServerStreamingServer[common.KvEventBatch]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeKvEvents not implemented")
}
func (UnimplementedVllmEngineServer) mustEmbedUnimplementedVllmEngineServer() {}
func (UnimplementedVllmEngineServer) testEmbeddedByValue()                    {}

// UnsafeVllmEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VllmEngineServer will
// result in compilation errors.
type UnsafeVllmEngineServer interface {
	mustEmbedUnimplementedVllmEngineServer()
}

func RegisterVllmEngineServer(s grpc.ServiceRegistrar, srv VllmEngineServer) {
	// If the following call pancis, it indicates UnimplementedVllmEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VllmEngine_ServiceDesc, srv)
}

func _VllmEngine_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VllmEngineServer).Generate(m, &grpc.GenericServerStream[GenerateRequest, GenerateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VllmEngine_GenerateServer = grpc.ServerStreamingServer[GenerateResponse]

func _VllmEngine_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VllmEngineServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VllmEngine_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VllmEngineServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VllmEngine_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VllmEngineServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VllmEngine_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VllmEngineServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VllmEngine_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VllmEngineServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VllmEngine_Abort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VllmEngineServer).Abort(ctx, req.(*AbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VllmEngine_GetModelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VllmEngineServer).GetModelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VllmEngine_GetModelInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VllmEngineServer).GetModelInfo(ctx, req.(*GetModelInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VllmEngine_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VllmEngineServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VllmEngine_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VllmEngineServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VllmEngine_GetTokenizer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(common.GetTokenizerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VllmEngineServer).GetTokenizer(m, &grpc.GenericServerStream[common.GetTokenizerRequest, common.GetTokenizerChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VllmEngine_GetTokenizerServer = grpc.ServerStreamingServer[common.GetTokenizerChunk]

func _VllmEngine_SubscribeKvEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(common.SubscribeKvEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VllmEngineServer).SubscribeKvEvents(m, &grpc.GenericServerStream[common.SubscribeKvEventsRequest, common.KvEventBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VllmEngine_SubscribeKvEventsServer = grpc.ServerStreamingServer[common.KvEventBatch]

// VllmEngine_ServiceDesc is the grpc.ServiceDesc for VllmEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VllmEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vllm.grpc.engine.VllmEngine",
	HandlerType: (*VllmEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embed",
			Handler:    _VllmEngine_Embed_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _VllmEngine_HealthCheck_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _VllmEngine_Abort_Handler,
		},
		{
			MethodName: "GetModelInfo",
			Handler:    _VllmEngine_GetModelInfo_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _VllmEngine_GetServerInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Generate",
			Handler:       _VllmEngine_Generate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTokenizer",
			Handler:       _VllmEngine_GetTokenizer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeKvEvents",
			Handler:       _VllmEngine_SubscribeKvEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vllm_engine.proto",
}
