// SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: trtllm_service.proto

package trtllm_service

import (
	context "context"
	common "github.com/lightseekorg/smg/crates/grpc_client/golang/smg_grpc_proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrtllmService_Generate_FullMethodName          = "/trtllm.TrtllmService/Generate"
	TrtllmService_Embed_FullMethodName             = "/trtllm.TrtllmService/Embed"
	TrtllmService_HealthCheck_FullMethodName       = "/trtllm.TrtllmService/HealthCheck"
	TrtllmService_Abort_FullMethodName             = "/trtllm.TrtllmService/Abort"
	TrtllmService_GetModelInfo_FullMethodName      = "/trtllm.TrtllmService/GetModelInfo"
	TrtllmService_GetServerInfo_FullMethodName     = "/trtllm.TrtllmService/GetServerInfo"
	TrtllmService_GetTokenizer_FullMethodName      = "/trtllm.TrtllmService/GetTokenizer"
	TrtllmService_SubscribeKvEvents_FullMethodName = "/trtllm.TrtllmService/SubscribeKvEvents"
)

// TrtllmServiceClient is the client API for TrtllmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrtllmServiceClient interface {
	// Generate tokens from pre-tokenized input
	// Returns a stream of responses containing token IDs
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error)
	// Generate embeddings from pre-tokenized input (for embedding models)
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	// Health check endpoint
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Abort a running generation request
	Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortResponse, error)
	// Get model information (vocab size, max lengths, etc.)
	GetModelInfo(ctx context.Context, in *GetModelInfoRequest, opts ...grpc.CallOption) (*GetModelInfoResponse, error)
	// Get server information (version, parallelism, etc.)
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error)
	// Get tokenizer artifacts for remote construction
	GetTokenizer(ctx context.Context, in *common.GetTokenizerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.GetTokenizerChunk], error)
	// Subscribe to KV cache events (server-streaming)
	SubscribeKvEvents(ctx context.Context, in *common.SubscribeKvEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.KvEventBatch], error)
}

type trtllmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrtllmServiceClient(cc grpc.ClientConnInterface) TrtllmServiceClient {
	return &trtllmServiceClient{cc}
}

func (c *trtllmServiceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrtllmService_ServiceDesc.Streams[0], TrtllmService_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrtllmService_GenerateClient = grpc.ServerStreamingClient[GenerateResponse]

func (c *trtllmServiceClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, TrtllmService_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trtllmServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, TrtllmService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trtllmServiceClient) Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*AbortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortResponse)
	err := c.cc.Invoke(ctx, TrtllmService_Abort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trtllmServiceClient) GetModelInfo(ctx context.Context, in *GetModelInfoRequest, opts ...grpc.CallOption) (*GetModelInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelInfoResponse)
	err := c.cc.Invoke(ctx, TrtllmService_GetModelInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trtllmServiceClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerInfoResponse)
	err := c.cc.Invoke(ctx, TrtllmService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trtllmServiceClient) GetTokenizer(ctx context.Context, in *common.GetTokenizerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.GetTokenizerChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrtllmService_ServiceDesc.Streams[1], TrtllmService_GetTokenizer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[common.GetTokenizerRequest, common.GetTokenizerChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrtllmService_GetTokenizerClient = grpc.ServerStreamingClient[common.GetTokenizerChunk]

func (c *trtllmServiceClient) SubscribeKvEvents(ctx context.Context, in *common.SubscribeKvEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.KvEventBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrtllmService_ServiceDesc.Streams[2], TrtllmService_SubscribeKvEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[common.SubscribeKvEventsRequest, common.KvEventBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrtllmService_SubscribeKvEventsClient = grpc.ServerStreamingClient[common.KvEventBatch]

// TrtllmServiceServer is the server API for TrtllmService service.
// All implementations must embed UnimplementedTrtllmServiceServer
// for forward compatibility.
type TrtllmServiceServer interface {
	// Generate tokens from pre-tokenized input
	// Returns a stream of responses containing token IDs
	Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error
	// Generate embeddings from pre-tokenized input (for embedding models)
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	// Health check endpoint
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Abort a running generation request
	Abort(context.Context, *AbortRequest) (*AbortResponse, error)
	// Get model information (vocab size, max lengths, etc.)
	GetModelInfo(context.Context, *GetModelInfoRequest) (*GetModelInfoResponse, error)
	// Get server information (version, parallelism, etc.)
	GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error)
	// Get tokenizer artifacts for remote construction
	GetTokenizer(*common.GetTokenizerRequest, grpc.ServerStreamingServer[common.GetTokenizerChunk]) error
	// Subscribe to KV cache events (server-streaming)
	SubscribeKvEvents(*common.SubscribeKvEventsRequest, grpc.ServerStreamingServer[common.KvEventBatch]) error
	mustEmbedUnimplementedTrtllmServiceServer()
}

// UnimplementedTrtllmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrtllmServiceServer struct{}

func (UnimplementedTrtllmServiceServer) Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedTrtllmServiceServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedTrtllmServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTrtllmServiceServer) Abort(context.Context, *AbortRequest) (*AbortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedTrtllmServiceServer) GetModelInfo(context.Context, *GetModelInfoRequest) (*GetModelInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelInfo not implemented")
}
func (UnimplementedTrtllmServiceServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedTrtllmServiceServer) GetTokenizer(*common.GetTokenizerRequest, grpc.ServerStreamingServer[common.GetTokenizerChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetTokenizer not implemented")
}
func (UnimplementedTrtllmServiceServer) SubscribeKvEvents(*common.SubscribeKvEventsRequest, grpc.ServerStreamingServer[common.KvEventBatch]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeKvEvents not implemented")
}
func (UnimplementedTrtllmServiceServer) mustEmbedUnimplementedTrtllmServiceServer() {}
func (UnimplementedTrtllmServiceServer) testEmbeddedByValue()                       {}

// UnsafeTrtllmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrtllmServiceServer will
// result in compilation errors.
type UnsafeTrtllmServiceServer interface {
	mustEmbedUnimplementedTrtllmServiceServer()
}

func RegisterTrtllmServiceServer(s grpc.ServiceRegistrar, srv TrtllmServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrtllmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrtllmService_ServiceDesc, srv)
}

func _TrtllmService_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrtllmServiceServer).Generate(m, &grpc.GenericServerStream[GenerateRequest, GenerateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrtllmService_GenerateServer = grpc.ServerStreamingServer[GenerateResponse]

func _TrtllmService_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrtllmServiceServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrtllmService_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrtllmServiceServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrtllmService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrtllmServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrtllmService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrtllmServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrtllmService_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrtllmServiceServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrtllmService_Abort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrtllmServiceServer).Abort(ctx, req.(*AbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrtllmService_GetModelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrtllmServiceServer).GetModelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrtllmService_GetModelInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrtllmServiceServer).GetModelInfo(ctx, req.(*GetModelInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrtllmService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrtllmServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrtllmService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrtllmServiceServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrtllmService_GetTokenizer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(common.GetTokenizerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrtllmServiceServer).GetTokenizer(m, &grpc.GenericServerStream[common.GetTokenizerRequest, common.GetTokenizerChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrtllmService_GetTokenizerServer = grpc.ServerStreamingServer[common.GetTokenizerChunk]

func _TrtllmService_SubscribeKvEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(common.SubscribeKvEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrtllmServiceServer).SubscribeKvEvents(m, &grpc.GenericServerStream[common.SubscribeKvEventsRequest, common.KvEventBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrtllmService_SubscribeKvEventsServer = grpc.ServerStreamingServer[common.KvEventBatch]

// TrtllmService_ServiceDesc is the grpc.ServiceDesc for TrtllmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrtllmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trtllm.TrtllmService",
	HandlerType: (*TrtllmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embed",
			Handler:    _TrtllmService_Embed_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _TrtllmService_HealthCheck_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _TrtllmService_Abort_Handler,
		},
		{
			MethodName: "GetModelInfo",
			Handler:    _TrtllmService_GetModelInfo_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _TrtllmService_GetServerInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Generate",
			Handler:       _TrtllmService_Generate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTokenizer",
			Handler:       _TrtllmService_GetTokenizer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeKvEvents",
			Handler:       _TrtllmService_SubscribeKvEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trtllm_service.proto",
}
